# Generated by Django 4.2.7 on 2025-10-17 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0002_alter_payment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='evidence_file',
            field=models.FileField(blank=True, null=True, upload_to='payment_evidence/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='shares_assigned',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('activation_fee', 'Activation Fee'), ('share_purchase', 'Share Purchase'), ('membership_fee', 'Membership Fee'), ('claim_payout', 'Claim Payout'), ('share_deduction', 'Share Deduction'), ('refund', 'Refund')], max_length=20),
        ),
    ]
