# Generated by Django 4.2.7 on 2025-10-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_admin_notes_payment_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('membership_single', 'Single Membership Fee'), ('membership_double', 'Double Membership Fee'), ('activation_fee', 'Activation Fee'), ('shares', 'Share Purchase'), ('claim_payout', 'Claim Payout'), ('share_deduction', 'Share Deduction'), ('refund', 'Refund'), ('other', 'Other')], max_length=20),
        ),
    ]
