# Generated by Django 4.2.7 on 2025-10-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('paypal', 'PayPal'), ('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer'), ('system', 'System Transaction')], max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('activation_fee', 'Activation Fee'), ('membership_single', 'Single Membership Fee'), ('membership_double', 'Double Membership Fee'), ('shares', 'Share Purchase'), ('share_purchase', 'Share Purchase'), ('membership_fee', 'Membership Fee'), ('claim_payout', 'Claim Payout'), ('share_deduction', 'Share Deduction'), ('other', 'Other Payment')], max_length=20),
        ),
    ]
