# Generated by Django 4.2.7 on 2025-10-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('paypal', 'PayPal'), ('venmo', 'Venmo'), ('zelle', 'Zelle'), ('debit_card', 'Debit Card'), ('credit_card', 'Credit Card'), ('mpesa', 'M-Pesa'), ('mobile_money', 'Mobile Money'), ('bank', 'Bank Transfer'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('check', 'Check'), ('system', 'System Transaction'), ('other', 'Other')], max_length=50),
        ),
    ]
