# Generated by Django 4.2.7 on 2025-10-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharetransaction',
            old_name='shares_count',
            new_name='shares_purchased',
        ),
        migrations.AddField(
            model_name='sharetransaction',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
