# Generated by Django 4.2.7 on 2025-10-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0002_rename_shares_count_sharetransaction_shares_purchased_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharetransaction',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
    ]
