# Generated by Django 4.2.7 on 2025-10-18 14:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0003_sharetransaction_admin_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharetransaction',
            name='buyer_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sharetransaction',
            name='payment_proof',
            field=models.FileField(blank=True, null=True, upload_to='share_payments/'),
        ),
        migrations.AlterField(
            model_name='sharetransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
