# Generated by Django 4.2.7 on 2025-10-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0004_sharetransaction_buyer_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharePurchase',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shares.sharetransaction',),
        ),
        migrations.RenameField(
            model_name='sharetransaction',
            old_name='shares_purchased',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='sharetransaction',
            old_name='amount',
            new_name='total_amount',
        ),
        migrations.RemoveField(
            model_name='sharetransaction',
            name='notes',
        ),
        migrations.AddField(
            model_name='sharetransaction',
            name='amount_per_share',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
    ]
