# Generated by Django 4.2.7 on 2025-10-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0005_sharepurchase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharetransaction',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sharetransaction',
            name='payment_method',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('venmo', 'Venmo'), ('zelle', 'Zelle'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('mpesa', 'M-Pesa'), ('cash', 'Cash'), ('other', 'Other')], max_length=50),
        ),
    ]
