# Generated by Django 4.2.7 on 2025-10-16 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('single', 'Single Family'), ('double', 'Double Family')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('confirm_email', models.EmailField(blank=True, max_length=254)),
                ('phone_main', models.CharField(blank=True, max_length=15)),
                ('address_1', models.CharField(max_length=200)),
                ('address_2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state_province', models.CharField(default='MN', max_length=50)),
                ('zip_postal', models.CharField(max_length=20)),
                ('spouse', models.CharField(blank=True, max_length=200)),
                ('spouse_phone', models.CharField(blank=True, max_length=15)),
                ('authorized_rep', models.CharField(blank=True, max_length=200)),
                ('child_1', models.CharField(blank=True, max_length=200)),
                ('child_2', models.CharField(blank=True, max_length=200)),
                ('child_3', models.CharField(blank=True, max_length=200)),
                ('child_4', models.CharField(blank=True, max_length=200)),
                ('child_5', models.CharField(blank=True, max_length=200)),
                ('parent_1', models.CharField(blank=True, max_length=200)),
                ('parent_2', models.CharField(blank=True, max_length=200)),
                ('spouse_parent_1', models.CharField(blank=True, max_length=200)),
                ('spouse_parent_2', models.CharField(blank=True, max_length=200)),
                ('sibling_1', models.CharField(blank=True, max_length=200)),
                ('sibling_2', models.CharField(blank=True, max_length=200)),
                ('sibling_3', models.CharField(blank=True, max_length=200)),
                ('declaration_accepted', models.BooleanField(default=False)),
                ('constitution_agreed', models.BooleanField(default=False)),
                ('id_document', models.FileField(blank=True, null=True, upload_to='applications/')),
                ('phone_legacy', models.CharField(blank=True, max_length=15)),
                ('address_legacy', models.TextField(blank=True)),
                ('state_legacy', models.CharField(blank=True, max_length=50)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
