# Generated by Django 4.2.7 on 2025-10-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_application_address_application_children_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='activation_fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=50.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='application',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
