# Generated by Django 4.2.7 on 2025-10-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_alter_application_activation_fee_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='emergency_relationship',
            field=models.CharField(blank=True, choices=[('spouse', 'Spouse'), ('parent', 'Parent'), ('sibling', 'Sibling'), ('child', 'Child'), ('friend', 'Friend')], max_length=50),
        ),
    ]
