# Generated by Django 4.2.7 on 2025-10-28 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('application_submitted', 'Application Submitted'), ('payment_made', 'Payment Made'), ('claim_submitted', 'Claim Submitted'), ('shares_purchased', 'Shares Purchased'), ('document_uploaded', 'Document Uploaded'), ('profile_updated', 'Profile Updated'), ('login', 'User Login'), ('logout', 'User Logout'), ('application_updated', 'Application Updated'), ('payment_updated', 'Payment Updated'), ('claim_updated', 'Claim Updated'), ('application_deleted', 'Application Deleted'), ('payment_deleted', 'Payment Deleted'), ('claim_deleted', 'Claim Deleted')], max_length=50)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
