# Generated by Django 4.2.7 on 2025-10-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claim',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='claim',
            name='supporting_documents',
            field=models.FileField(blank=True, null=True, upload_to='claims/'),
        ),
    ]
