# Generated by Django 4.2.7 on 2025-10-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_alter_claim_options_claim_supporting_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='claim_type',
            field=models.CharField(choices=[('death', 'Death Benefit'), ('medical', 'Medical Emergency'), ('education', 'Education Support'), ('emergency', 'Emergency Assistance')], max_length=20),
        ),
        migrations.AlterField(
            model_name='claim',
            name='relationship',
            field=models.CharField(choices=[('self', 'Self'), ('spouse', 'Spouse'), ('child', 'Child'), ('parent', 'Parent'), ('sibling', 'Sibling')], max_length=50),
        ),
    ]
