# Generated by Django 4.2.7 on 2025-10-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='available_shares',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='user',
            name='deactivation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='shares_owned',
            field=models.IntegerField(default=0),
        ),
    ]
