# Generated by Django 4.2.7 on 2025-10-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_available_shares_user_deactivation_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='available_shares',
            field=models.IntegerField(default=0),
        ),
    ]
