# Generated by Django 4.2.7 on 2025-10-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active_member',
            field=models.BooleanField(default=False),
        ),
    ]
