# Generated by Django 4.2.7 on 2025-10-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_is_active_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='membership_type',
            field=models.CharField(blank=True, choices=[('single', 'Single Membership'), ('double', 'Double Membership')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='shares',
            field=models.IntegerField(default=0),
        ),
    ]
